### ISSUE TITLE
Create world and room classes to store information about the world

### ISSUE THREAD

**Issue by Lathie** [GalaxionTeam/galaxion-engine#20]
See the picture in messenger for a general outline

**Comment by nirm123** [comment]
I'm a bit confused about the structure of these classes. Does room just have general information about a room, or is it an array of objects representing the specifics of each coordinate in a room?

**Comment by emordonez** [comment]
I think it'd be simplest to have the room have general information about itself. Are we considering each room to be a single point in the coordinate grid, or can a room cover multiple points?

**Comment by nirm123** [comment]
So right now what I've done is made a room class which contains an array of objects of class coordinate. The coordinate class would then store like info about what is at a specific point. Again, I'm not sure if that's a good idea. You can check it out in my branch.

**Comment by Lathie** [comment]
I think what we discussed was to have World be a 2d array of Rooms, in this way, you can look up a specific room with their X and Y coords using the World Object. There isn't really a need to create a coordinate class or anything like that

**Comment by nirm123** [comment]
Okay, so what is included in the room class?

**Comment by Lathie** [comment]
For sure a description of the room, probably an array of items but that doesn't have to be made yet

**Comment by emordonez** [comment]
Maybe instance variables for name, location, description, and a list of items contained in the room?

**Comment by Lathie** [comment]
:+1: Name

**Comment by nirm123** [comment]
I think I was overthinking things. Can a player move around within a room?

**Comment by Lathie** [comment]
No, a room is just an location

**Comment by nirm123** [comment]
Cool
